InstWeb/Models/Alumno.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace InstWeb.Models
{
    public class Alumno
    {
        [Key]
        public Guid ID { get; set; }

        [Required]
        [MaxLength(50)]
        public string Nombre { get; set; }

        [Required]
        [MaxLength(50)]
        public string Apellido { get; set; }

        [MaxLength(200)]
        public string Email { get; set; }

        [MaxLength(200)]
        public string Domicilio { get; set; }

        [MaxLength(10)]
        public string Telefono { get; set; }

        [Display(Name = "Fecha Nac.")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? FechaNacimiento { get; set; }

        public int? DNI { get; set; }

        [Required(ErrorMessage = "Debe ingresar el legajo")]
        [MaxLength(50)]
        public string Legajo { get; set; }

        [MaxLength(200)]
        public string Localidad { get; set; }
    }
}

InstWeb/Controllers/AlumnosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using InstWeb.Data;
using InstWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace InstWeb.Controllers
{
    public class AlumnosController : Controller
    {
        private InstitutoContext _context;

        public AlumnosController(InstitutoContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            IEnumerable<Alumno> alumnos = _context.Alumnos;
            return View(alumnos);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Guardar([Bind("Nombre,Apellido,Email,Domicilio,Telefono,FechaNacimiento,DNI,Legajo")] Alumno alumno)
        {
            alumno.ID = Guid.NewGuid();

            _context.Alumnos.Add(alumno);
            _context.SaveChanges();

            GuardarAlumnoEnSession(alumno);

            return View("Details", alumno);
        }

        public IActionResult Edit(Guid id)
        {
            Alumno alumnoEditar = _context.Alumnos.Find(id);
            return View(alumnoEditar);
        }

        [HttpPost]
        public IActionResult Edit([Bind("ID,Nombre,Apellido,Email,Domicilio,Telefono,FechaNacimiento,DNI,Legajo")] Alumno alumno)
        {
            _context.Alumnos.Update(alumno);
            _context.SaveChanges();

            return View(alumno);
        }

        // GET: Alumnos/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var alumno = _context.Alumnos.FirstOrDefault(m => m.ID == id);
            if (alumno == null)
            {
                return NotFound();
            }

            return View(alumno);
        }

        public void GuardarAlumnoEnSession(Alumno alumnoAGuardar)
        {
            HttpContext.Session.Set<Alumno>("AlumnoActivo", alumnoAGuardar);
        }

        public JsonResult VerAlumnoEnSession()
        {
            Alumno alumnoEnSession = HttpContext.Session.Get<Alumno>("AlumnoActivo");
            return Json(alumnoEnSession);
        }
    }
}

InstWeb/Views/Alumnos/Create.cshtml
<h1>Crear Alumnos</h1>
<form asp-action="Guardar" asp-controller="Alumnos" method="post">
    <div>
        <label for="nombre">Nombre</label>
        <input type="text" id="nombre" name="nombre" required />
    </div>
    <div>
        <label for="apellido">Apellido</label>
        <input type="text" id="apellido" name="apellido" required />
    </div>
    <div>
        <label for="email">Email</label>
        <input type="email" id="email" name="email" required />
    </div>
        <label for="domicilio">Domicilio</label>
        <input type="text" id="domicilio" name="domicilio" required />
    <div>
    </div>
        <label for="telefono">Telefono</label>
        <input type="text" id="telefono" name="telefono" required />
    <div>
        <label for="fechaNacimiento">Fecha Nacimiento</label>
        <input type="date" id="fechaNacimiento" name="fechaNacimiento" required />
    </div>
    <div>
        <label for="dni">DNI</label>
        <input type="number" id="dni" name="dni" required />
    </div>
    <div>
        <label for="legajo">Legajo</label>
        <input type="text" id="legajo" name="legajo" required />
    </div>

    <div>
        <input type="submit" value="Guardar">
    </div>
</form>

InstWeb/Views/Alumnos/Details.cshtml
@model Alumno

@{
    ViewData["Title"] = "Detalle";
}

<h1>Detalle</h1>

<div>
    <h4>Alumno</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Domicilio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Domicilio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DNI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Legajo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Legajo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    <a asp-action="Index">Volver</a> |
    @Html.ActionLink("Ver Cookie", "VerAlumnoEnSession")
</div>

InstWeb/Views/Alumnos/Edit.cshtml
@model Alumno

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Alumno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Domicilio" class="control-label"></label>
                <input asp-for="Domicilio" class="form-control" />
                <span asp-validation-for="Domicilio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DNI" class="control-label"></label>
                <input asp-for="DNI" class="form-control" />
                <span asp-validation-for="DNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Legajo" class="control-label"></label>
                <input asp-for="Legajo" class="form-control" />
                <span asp-validation-for="Legajo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InstWeb/Views/Alumnos/Index.cshtml
@model IEnumerable<Alumno>

@{
    ViewData["Title"] = "Alumnos";
}

<h1>Alumnos</h1>

<p>
    <a asp-action="Create">Crear Nuevo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Legajo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Domicilio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DNI)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Legajo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Apellido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Domicilio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefono)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaNacimiento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DNI)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id=item.ID }) |
                    @Html.ActionLink("Detalle", "Details", new { id=item.ID }) |
                    @Html.ActionLink("Eliminar", "Delete", new { id=item.ID })
                </td>
            </tr>
        }
    </tbody>
</table>